[project]
name = "fixedpointnumbers"
version = "0.1.0"
description = "The fixedpointnumbers package"
license = "MIT"

[remote]
author = "[AUTHOR]" # Add your Aleo Package Manager username or team name.
